# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  ################
  # VM 전역 설정  #
  ################
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_version = "4.3.12"

  # 패키지 설치는 초기 한번만 수행하는 옵션 run
  config.vm.provision "shell", path: "pre_install.sh", name: "package_update", run: "once"

  config.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = true  # GUI를 활성화하면 VMware 앱에서 서버 만들어지는 것이 보임
      vmware.memory = "2048"  # 2GB 메모리 할당
      vmware.cpus = 2         # 2개의 CPU 코어 할당
    end

  ################
  # VM 개별 설정  #
  ################

  # Ansible 서버
  config.vm.define "ansible-server" do |ansible|
    ansible.vm.hostname = "ansible-server"
    ansible.vm.network "public_network", ip: "192.168.56.10"
    # Ansible 설치 및 확인
    ansible.vm.provision "shell", path: "install_ansible.sh", name: "install_ansible", run: "once"

    # 동일 경로의 Ansible 플레이북 파일을 서버 내부로 이동해 실행
    ansible.vm.provision "file", source: "ansible_env_ready.yml", destination: "ansible_env_ready.yml"
    ansible.vm.provision "shell", inline: "ansible-playbook ansible_env_ready.yml"
  end

  # Kubernetes 마스터 노드
  config.vm.define "k8s-master" do |master|
    master.vm.hostname = "k8s-master"
    master.vm.network "public_network", ip: "192.168.56.11"
    # Kubernetes API Server (6443): 외부에서 Kubernetes API에 접근할 때 필요한 포트
    master.vm.network "forwarded_port", guest: 6443, host: 6443, id: "k8s_api_server"

    # Kubelet (10250): Kubernetes 노드와 상호작용할 때 사용
    master.vm.network "forwarded_port", guest: 10250, host: 10250, id: "kubelet"
  end

  # Kubernetes 워커 노드
  (1..2).each do |i|
    config.vm.define "k8s-worker#{i}" do |worker|
      worker.vm.hostname = "k8s-worker#{i}"
      worker.vm.network "public_network", ip: "192.168.56.1#{i+1}"
    end
  end
end