# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  ################
  # VM 전역 설정  #
  ################
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_version = "4.3.12"

#   config.vm.network "public_network", type: "dhcp"
  
  config.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = true  # GUI를 활성화해야 VMware Workstation 어플리케이션에 자동 등록
      vmware.memory = "2048"  # 2GB 메모리 할당
      vmware.cpus = "2"         # 2개의 CPU 코어 할당
    end

  ################
  # VM 개별 설정  #
  ################

  # Kubernetes 마스터 노드
  config.vm.define "k8s-master" do |master|
    master.vm.hostname = "vm-master"
#     master.vm.network "private_network"

    # NAT 인터페이스로 구성했다면 호스트 머신에서도 kubectl을 사용하기 위해 포트포워딩
    # master.vm.network "forwarded_port", guest: 6443, host: 6443, id: "k8s_api_server" # Kubernetes API Server (6443): 외부에서 Kubernetes API에 접근할 때 필요한 포트
    # 만약 가상 머신이 외부 클러스터에 참여해야 한다면 kubelet도 포트포워딩
    # kubelet (10250) : "Kubernetes 워커 노드가 마스터 노드와 상호작용할 때 사용"
  end

  # Kubernetes 워커 노드
  (1..3).each do |i|
    config.vm.define "k8s-worker#{i}" do |worker|
      worker.vm.hostname = "vm-worker#{i}"
#       worker.vm.network "private_network"
    end
  end

    # kubelet, kubeadm, kubectl 패키지 공통 설치를 위한 스크립트
    config.vm.provision "shell", path: "k8s_node_install.sh", name: "package_update", run: "once"
    # 공통 설치를 하는 이유는 마스터 <-> 워커 상호간 버전이 달라도 문제가 생기고
    # kubelet <-> kubeadm 패키지간 버전 차이가 발생해도 문제가 출력됩니다.
end